###
POST http://localhost:8080/order
Content-Type: application/json

{
  "userName": "test",
  "orderItemRequests": [
    {"itemId": 1, "stock" : 1},
    {"itemId": 2, "stock" : 2},
    {"itemId": 3, "stock" : 3}
  ]
}

###
POST http://localhost:8080/order
Content-Type: application/json

{
  "userName": "test",
  "orderItemRequests": [
    {"itemId": 4, "stock" : 1},
    {"itemId": 5, "stock" : 2},
    {"itemId": 6, "stock" : 3}
  ]
}


###
GET http://localhost:8080/orders?userName=test

###
PUT http://localhost:8080/order/ship?id=1

###
PUT http://localhost:8080/order/cancel?id=2
